### ISSUE TITLE
Use with JupyterLite

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab-plugin-playground#16]
### Problem

Out of curiosity I checked whether that playground would work in JupyterLite, and it did!

Which means that folks can try the examples and write plugins very quickly.

![image](https://user-images.githubusercontent.com/591645/137467405-1c319358-6213-4d2f-9a1e-98f9cefdb5e5.png)

### Proposed Solution

Maybe we could have a JupyterLite deployment with this extension installed, so it's easier to try things out without spinning up a JupyterLab server locally or launch a Binder?

We could then share paths to a specific file, for example (on my custom lite deployment):

- with JupyterLab: https://jtpio.github.io/lit/lab/index.html?path=plugin.txt
- with RetroLab: https://jtpio.github.io/lit/retro/edit/?path=plugin.txt

With RTC enabled, that would also mean being able to help folks in real time for example when explaining something about the plugin system of JupyterLab: https://jtpio.github.io/lit/lab/index.html?path=plugin.txt&room=yourcustomroomhere

### Additional context

Deploying a lite web site to the GitHub Pages of the same repo might increase its weight, as a couple of MBs are shipped each time.

Instead it could be deployed on ReadTheDocs (might need https://github.com/jupyterlite/jupyterlite/issues/149 first for convenience).

**Comment by bollwyvl** [comment]
And extending the `Load Current File As Extension` to JS-kernel notebooks would make _incredible_ tutorials.
