### ISSUE TITLE
Release with the Jupyter Releaser

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab-plugin-playground#29]
### Problem

- The extension is already packaged as a prebuilt extension for JupyterLab 3.0
- There is also the Check Release now running on PRs and commits: https://github.com/jupyterlab/jupyterlab-plugin-playground/actions/workflows/check-release.yml

So the repo should already be compatible with the Jupyter Releaser.

### Proposed Solution

We can then publish the next version of `jupyterlab-plugin-playground` with the releaser.

### Additional context

I'm happy to do the next release. Some exciting work by @krassowski is coming up in https://github.com/jupyterlab/jupyterlab-plugin-playground/pull/28, and it will be great to have it released after the PR is merged.

cc @jasongrout @blink1073 I would need write access to the PyPI package to be able to publish there: https://pypi.org/project/jupyterlab-plugin-playground/

**Comment by blink1073** [comment]
> cc @jasongrout @blink1073 I would need write access to the PyPI package to be able to publish there: pypi.org/project/jupyterlab-plugin-playground

Invite sent!

**Comment by jtpio** [comment]
Thanks!

**Comment by jtpio** [comment]
Closing as fixed since `0.4.0` was released with the releaser: https://github.com/jupyterlab/jupyterlab-plugin-playground/releases/tag/v0.4.0
